//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MateuszThomasZad5WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tasks
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public System.DateTime Deadline { get; set; }
        public int StudentID { get; set; }
    
        public virtual Students Students { get; set; }
    }
}
